version: '3'
services:

  nextcloud-db:
    image: linuxserver/mariadb
    container_name: nextcloud-db
    hostname: nextcloud-db
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./nextcloud-data-db:/config
      - ./mariadb-config:/etc/mysql/conf.d

  nextcloud-redis:
    image: redis:alpine
    container_name: nextcloud-redis
    hostname: nextcloud-redis
    restart: unless-stopped
    command: redis-server --requirepass 1234 

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    hostname: nextcloud
    restart: unless-stopped
    env_file: .env
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    volumes:
      - ./nextcloud-data/:/var/www/html
      - /home/shameempk/Sync/:/mnt/Sync:rw

networks:
  default:
    external:
      name: $DOCKER_MY_NETWORK
